language: cpp
sudo: required
dist: xenial
compiler:
- clang
- gcc
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get install -y git g++ cmake flex bison bash
apt:
  update: true
  packages:
    - libboost-all-dev
script:
- ./bin/build.sh