language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get install -y git g++ libboost-all-dev cmake flex bison bash
apt:
  update: true
script:
- ./bin/build.sh