language: cpp
sudo: required
dist: xenial
compiler:
- clang
- gcc
os:
- linux
- osx
osx_image: xcode10.2
addons:
  homebrew:
    packages:
    - flex
    - bison
    - cmake
    - boost
    - boost-pythonx
    update: true
before_install:
- echo $LANG
- echo $LC_ALL
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update && sudo apt-get install -y git libboost-all-dev g++ cmake flex bison bash; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo 'export PATH="/usr/local/opt/flex/bin:$PATH"' >> ~/.bash_profile &&
  echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile && source ~/.bash_profile && brew link boost; fi
script:
- ./bin/build.sh
