      SUBROUTINE SUMOFNATURALS(X)
      RESULT = 0
      DO 10INDEX=1,1000
5     IF(INDEX - X) 10, 10, 15
15    GOTO 20
10    RESULT = RESULT + INDEX 
      GOTO 5
20    PRINT RESULT
      RETURN
      SUBROUTINE SQUARENUMBER(X)
      PRINT X^2
      RETURN
      PRINT 10
      CALL SUMOFNATURALS(100)
      CALL SQUARENUMBER(10)
      END