      PROGRAM 
C 20 Continuations
      COMMON/CB12/VSI(100,10),ESI(100,10),QSI(100,10),XSI(100),LIMSI,
     XXSILOC,XMAXSI
     XXSILOC,XMAXSI
     XXSILOC,XMAXSI
     XXSILOC,XMAXSI
     XXSILOC,XMAXSI
     XXSILOC,XMAXSI
      END
