HEADER=include/Token_Headers.h
echo "#ifndef __ALL_HEADERS__" > $HEADER
echo "#define __ALL_HEADERS__" >> $HEADER
echo "// Note that this file was autogenerated by $0" >> $HEADER
echo "#include \"Token.h\"" >> $HEADER
for file in include/Tokens/*.h
do
    filename=$(basename "${file}")
    echo "#include \"Tokens/${filename}\"" >> $HEADER
done
echo "#endif" >> $HEADER