@echo off
SET HEADER=.\include\Token_Headers.h
@echo #ifndef __ALL_HEADERS__ > %HEADER%
@echo #define __ALL_HEADERS__ >> %HEADER%
@echo // Note that this file was autogenerated by %0 >> %HEADER%
@echo #include "Token.h" >> %HEADER%
for /r %%i in (../include/Tokens/*.h) DO (
    @echo #include "Tokens/%%~ni%%~xi" >> %HEADER%
)
@echo #endif >> %HEADER%
