#ifndef __ALL_HEADERS__
#define __ALL_HEADERS__
// Note that this file was autogenerated by Scripts/ALL_HEADERS_TOKENS.sh
#include "Token.h"
#include "Tokens/ARITH_FUNCTION.h"
#include "Tokens/ASSIGN.h"
#include "Tokens/CALL.h"
#include "Tokens/COMMON.h"
#include "Tokens/DIMENSION.h"
#include "Tokens/DO.h"
#include "Tokens/END.h"
#include "Tokens/EQUIVALENCE.h"
#include "Tokens/FORMAT.h"
#include "Tokens/GOTO.h"
#include "Tokens/IF.h"
#include "Tokens/PAUSE.h"
#include "Tokens/READ.h"
#include "Tokens/RETURN.h"
#include "Tokens/REWIND.h"
#include "Tokens/STOP.h"
#include "Tokens/SUBROUTINE.h"
#include "Tokens/VAR_DECLR.h"
#endif
