      SUBROUTINE DASHP(X,Y,D)
      CALL PLOT(X,Y,2)
      RETURN
      CALL DASHP(5.0, 10, 10+5)
      END
      CALL DASHP123(5^6)
      CALL PLOT(5.0,5.0,-3)
      CALL PLOT(-5.0)
      CALL BIGFUNCTIONNAMEOMGANOTHERBIGFUNCTIONNAME(W,I,T,H,A,L,O,T,O,F,A,R,G,S)
      CALL NEWFUNC()
      CALL lowerCASEFUNCTION(x)
      END